Repository apify/apify-cli, pull requests merged in 2022-11, with the labels that each got.

#293 feat: updated input schema package
  CONTRIBUTING.md
  README.md
  npm-shrinkwrap.json
  oclif.manifest.json
  package.json
Labels: adhoc, t-console

#285 chore: update GitHub actions
  .github/workflows/check.yml
  .github/workflows/release.yml
Labels: t-platform

#286 feat: Add hidden `edit-input-schema` command
  npm-shrinkwrap.json
  oclif.manifest.json
  package.json
  src/commands/edit-input-schema.js
Labels: adhoc, t-platform
