Repository apify/apify-cli, pull requests merged in 2023-11, with the labels that each got.

#396 ci: improve CI setup (+use new favicon)
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
  .gitignore
  website/docusaurus.config.js
Labels: adhoc, debt, t-tooling

#411 docs: update docusaurus to v2.4.3
  .github/workflows/docs.yaml
  website/package-lock.json
  website/package.json
Labels: adhoc, debt, t-tooling

#414 chore: update linter + some other dependencies
  npm-shrinkwrap.json
  package.json
  src/commands/actor/get-input.js
  src/commands/actor/get-value.js
  src/commands/actor/index.js
  src/commands/actor/push-data.js
  src/commands/actor/set-value.js
  src/commands/call.js
  src/commands/check-version.js
  src/commands/create.js
  src/commands/edit-input-schema.js
  src/commands/info.js
  src/commands/init.js
  src/commands/login-new.js
  src/commands/login.js
  src/commands/logout.js
  src/commands/pull.js
  src/commands/push.js
  src/commands/run.js
  src/commands/secrets/index.js
  src/commands/vis.js
  src/lib/actor.js
  src/lib/apify_command.js
  src/lib/consts.js
  src/lib/create-utils.js
  src/lib/exec.js
  src/lib/files.js
  src/lib/input_schema.js
  src/lib/local_state.js
  src/lib/secrets.js
  src/lib/telemetry.js
  src/lib/utils.js
  src/lib/version_check.js
  test/commands/call.js
  test/commands/config.js
  test/commands/create.js
  test/commands/info.js
  test/commands/init.js
  test/commands/log_in_out.js
  test/commands/pull.js
  test/commands/push.js
  test/commands/run.js
  test/commands/secrets/add.js
  test/commands/secrets/rm.js
  test/commands/vis.js
  test/consts.js
  test/python_support.js
  test/secrets.js
  test/templates.js
  test/utils.js
  test/version_check.js
  website/package-lock.json
  website/package.json
Labels: adhoc, debt, t-tooling

#434 refactor: track Scrapy wrapper usage using mixpanel
  src/commands/init.js
Labels: adhoc, t-tooling

#435 chore: bump version
  npm-shrinkwrap.json
  package.json
Labels: adhoc, t-tooling

#437 fix: restore fallback behaviour for apify run in Scrapy projects
  oclif.manifest.json
  src/commands/run.js
Labels: adhoc, t-tooling

#438 chore: bump package version
  npm-shrinkwrap.json
  package.json
Labels: adhoc, t-tooling

#440 docs: add feedback invitation in integrating-scrapy
  docs/integrating-scrapy.md
Labels: documentation, adhoc, t-tooling
