Repository apify/apify-cli, pull requests merged in 2023-05, with the labels that each got.

#361 chore: Use new workflow secrets
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
Labels: adhoc, t-platform

#363 feat: add community message
  package.json
  src/lib/community.js
Labels: t-web

#364 fix: Use the right exit code on error
  src/bin/run
Labels: bug, adhoc, t-platform

#365 feat(push): allow disabling of the prompt mechanism via flag/CI
  npm-shrinkwrap.json
  package.json
  src/commands/push.js
Labels: t-tooling

#366 fix(push): correctly check if in CI env to skip prompt
  src/commands/push.js
Labels: t-tooling
