Repository apify/apify-cli, pull requests merged in 2023-03, with the labels that each got.

#341 chore: Don't use `npm` in latest version check
  npm-shrinkwrap.json
  package.json
  src/commands/create.js
  src/lib/version_check.js
  test/version_check.js
Labels: adhoc, t-platform

#342 feat: Print correct update command based on package manager
  src/lib/version_check.js
Labels: adhoc, t-platform

#343 Prepare for release on Homebrew
  .github/workflows/release.yml
  README.md
  docs/installation.md
Labels: adhoc, t-platform

#344 Add automated tests for Python support
  .github/workflows/check.yml
  .github/workflows/release.yml
  package.json
  test/python_support.js
Labels: t-platform

#345 Improvements to Homebrew support
  src/commands/create.js
  src/commands/run.js
  src/lib/utils.js
  src/lib/version_check.js
Labels: adhoc, t-platform

#346 Use correct "omit optional dependencies" argument based on NPM version
  src/commands/create.js
  src/lib/utils.js
Labels: adhoc, debt, t-platform

#347 Update the `apify run` help to not be so Node-specific
  README.md
  oclif.manifest.json
  src/commands/run.js
Labels: adhoc, t-platform

#349 feat: Add a post-create message to Python actors
  src/commands/create.js
Labels: adhoc, t-platform

#350 Improve log messages for different build statuses
  src/commands/push.js
  src/lib/utils.js
Labels: bug, adhoc, t-platform

#354 chore: Unify YAML file extensions to .yaml
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  .github/workflows/pr_toolkit.yaml
  .github/workflows/release.yaml
Labels: t-platform
