Repository apify/apify-cli, pull requests merged in 2023-04, with the labels that each got.

#353 feat(app): Open actor detail after successful apify push
  src/commands/push.js
Labels: t-web

#355 feat: Don't add `apify_storage` to .gitignore if it already is there
  npm-shrinkwrap.json
  package.json
  src/lib/utils.js
Labels: adhoc, t-platform

#357 feat: Improve `apify login-new` command
  src/commands/login-new.js
Labels: adhoc, t-platform

#359 fix: Fix `apify create` on Node 19+, add Node 20 to CI test roster
  .github/workflows/check.yaml
  .github/workflows/release.yaml
  README.md
  npm-shrinkwrap.json
  oclif.manifest.json
  package.json
  src/lib/create-utils.js
  test/commands/vis.js
Labels: bug, adhoc, t-platform
