Repository apify/apify-cli, pull requests merged in 2023-01, with the labels that each got.

#308 fix: fix headings in readme
  .nvmrc
  README.md
  npm-shrinkwrap.json
  oclif.manifest.json
  package.json
Labels: bug, adhoc

#318 chore: Disable actor template prompt looping around
  src/commands/create.js
Labels: bug, adhoc

#316 feat: Support for running Python actors
  README.md
  oclif.manifest.json
  src/commands/call.js
  src/commands/create.js
  src/commands/push.js
  src/commands/run.js
  src/lib/consts.js
  src/lib/utils.js
Labels: adhoc

#322 fix: Removing unneeded dependencies
  README.md
  npm-shrinkwrap.json
  oclif.manifest.json
  package.json
Labels: adhoc, t-platform
