Repository apify/apify-cli, pull requests merged in 2023-12, with the labels that each got.

#455 docs: better guide for Scrapy migrations
  docs/index.md
  docs/installation.md
  docs/integrating-scrapy.md
  website/src/pages/index.js
Labels: documentation, t-tooling

#456 docs: Update capitalization integrating-scrapy.md
  docs/integrating-scrapy.md
Labels: adhoc, t-platform

#463 chore: move from mocha to vitest
  .gitignore
  npm-shrinkwrap.json
  package.json
  test/.eslintrc.json
  test/commands/call.js
  test/commands/create.js
  test/commands/info.js
  test/commands/init.js
  test/commands/log_in_out.js
  test/commands/pull.js
  test/commands/push.js
  test/commands/run.js
  test/commands/secrets/add.js
  test/commands/secrets/rm.js
  test/commands/vis.js
  test/consts.js
  test/python_support.js
  test/secrets.js
  test/templates.js
  test/tsconfig.json
  test/utils.js
  test/version_check.js
  vitest.config.ts
Labels: adhoc, t-tooling, tested

#466 feat: extend success command on create
  src/commands/create.js
Labels: t-web
