Repository apify/apify-cli, pull requests merged in 2023-07, with the labels that each got.

#379 feat(create, init): create INPUT.json from input_schema prefills
  src/commands/create.js
  src/commands/init.js
  src/lib/create-utils.js
  src/lib/input_schema.js
  src/lib/utils.js
  test/commands/call.js
  test/commands/create.js
  test/commands/init.js
  test/commands/run.js
Labels: adhoc, t-web

#381 feat: Use actor/apify env vars instead of old `ENV_VARS`
  npm-shrinkwrap.json
  package.json
  src/commands/run.js
  src/lib/actor.js
  src/lib/utils.js
  test/commands/run.js
Labels: t-platform

#382 chore: Bump version to 0.18.0
  README.md
  npm-shrinkwrap.json
  oclif.manifest.json
Labels: adhoc, t-platform
