Repository apify/apify-cli, pull requests merged in 2024-09, with the labels that each got.

#625 fix: ensure input kvs path exists when calling `apify run`
  package.json
  src/commands/run.ts
  yarn.lock
Labels: adhoc, t-tooling

#626 chore: bump version
  package.json
Labels: adhoc, t-tooling

#627 chore: prepare for next release
  package.json
Labels: adhoc, t-tooling

#628 chore: don't tag fnesveda on new Homebrew releases
  .github/workflows/check.yaml
Labels: adhoc, t-platform

#629 docs: bump Docusaurus@v3
  website/package.json
  website/yarn.lock
Labels: adhoc, t-tooling

#632 feat: bootstrap new command namespaces
  src/commands/actors/index.ts
  src/commands/datasets/index.ts
  src/commands/key-value-stores/index.ts
  src/commands/request-queues/index.ts
  src/commands/runs/index.ts
Labels: adhoc, t-tooling

#641 fix: auto-set `apify run` `INPUT.json` only with values that have defaults
  src/commands/run.ts
  src/lib/input_schema.ts
  test/commands/run.test.ts
Labels: t-tooling, tested

#620 feat: builds namespace
  .github/workflows/cucumber.yaml
  features/builds-namespace.feature.md
  features/test-implementations/0.utils.ts
  features/test-implementations/0.world.ts
  features/test-implementations/1.setup.ts
  features/test-implementations/2.execution.ts
  features/test-implementations/3.results.ts
  features/test-implementations/README.md
  package.json
  src/commands/builds/create.ts
  src/commands/builds/index.ts
  src/commands/builds/info.ts
  src/commands/builds/log.ts
  src/commands/builds/ls.ts
  src/lib/apify_command.ts
  src/lib/commands/pretty-print-bytes.ts
  src/lib/commands/pretty-print-status.ts
  src/lib/commands/resolve-actor-context.ts
  src/lib/utils.ts
  yarn.lock
Labels: adhoc, t-tooling

#639 chore: add in automatic issue labeler
  .github/workflows/issue_labeling.yaml
Labels: adhoc, t-tooling

#640 feat: `runs ls`
  .github/workflows/check.yaml
  package.json
  src/commands/builds/ls.ts
  src/commands/create.ts
  src/commands/run.ts
  src/commands/runs/ls.ts
  src/lib/commands/responsive-table.ts
  src/lib/consts.ts
  yarn.lock
Labels: adhoc, t-tooling

#643 feat: `runs abort`
  src/commands/runs/abort.ts
Labels: adhoc, t-tooling

#644 feat: `runs resurrect`
  src/commands/runs/resurrect.ts
Labels: adhoc, t-tooling

#645 feat: `runs log`
  src/commands/runs/log.ts
Labels: adhoc, t-tooling

#648 feat: `runs rm` & `builds rm` & `actors rm`
  src/commands/actors/rm.ts
  src/commands/builds/info.ts
  src/commands/builds/rm.ts
  src/commands/runs/rm.ts
  src/lib/commands/confirm.ts
Labels: adhoc, t-tooling

#661 feat: `actors build`
  src/commands/actors/build.ts
  src/commands/builds/create.ts
Labels: adhoc, t-tooling

#662 feat: `actors pull`
  src/commands/actors/pull.ts
  src/commands/pull.ts
  src/lib/apify_command.ts
  src/lib/consts.ts
  test/commands/pull.test.ts
Labels: adhoc, t-tooling, tested

#663 feat: `actors call`
  src/commands/actors/call.ts
  src/commands/call.ts
  src/commands/runs/info.ts
  src/commands/task/run.ts
  src/lib/commands/run-on-cloud.ts
  src/lib/utils.ts
  test/commands/call.test.ts
Labels: adhoc, t-tooling, tested

#665 chore: several tweaks
  src/commands/actors/call.ts
  src/commands/builds/create.ts
  src/commands/builds/ls.ts
  src/commands/push.ts
  src/commands/runs/abort.ts
  src/commands/runs/info.ts
  src/commands/runs/log.ts
  src/commands/runs/ls.ts
  src/commands/runs/resurrect.ts
  src/commands/task/run.ts
  src/lib/commands/run-on-cloud.ts
Labels: adhoc, t-tooling

#667 feat: check if cli was installed using volta when checking for updates
  src/lib/version_check.ts
Labels: adhoc, t-tooling

#668 chore: fix cucumber tests for builds namespace
  features/builds-namespace.feature.md
  features/test-implementations/3.results.ts
  features/test-implementations/README.md
  src/commands/builds/create.ts
  src/commands/builds/info.ts
  src/commands/builds/log.ts
  src/commands/builds/rm.ts
Labels: adhoc, t-tooling
