Repository apify/apify-cli, pull requests merged in 2024-02, with the labels that each got.

#475 chore: support new crawlee purge logic
  src/commands/run.js
  src/lib/consts.js
  src/lib/project_analyzer.js
  src/lib/projects/CrawleeAnalyzer.js
  src/lib/projects/OldApifySDKAnalyzer.js
  src/lib/utils.js
Labels: t-tooling

#481 fix: axios v1 and new client breaking cli
  npm-shrinkwrap.json
  package.json
  src/lib/utils.js
Labels: adhoc, t-tooling

#484 docs: add a simple troubleshooting page with our contact
  docs/troubleshooting.md
  website/sidebars.js
Labels: adhoc, t-platform

#491 feat: add a troubleshooting section to the root help screen
  npm-shrinkwrap.json
  package.json
  src/lib/apify-oclif-help.js
Labels: t-platform

#500 chore: fix ci script
  .github/scripts/before-beta-release.ts
  .github/workflows/check.yaml
  vitest.config.ts
Labels: adhoc, t-tooling, tested

#502 chore: fix CI again
  .github/workflows/check.yaml
  test/commands/secrets/add.test.ts
  test/commands/secrets/rm.test.ts
Labels: adhoc, t-tooling, tested

#503 chore: regenerate website reference when releasing
  package.json
Labels: t-tooling

#505 chore: bring back apify -v and apify -h
  package.json
Labels: adhoc, t-tooling

#504 fix: prompt for new folder name when existing folder is used with `apify create`
  src/commands/create.ts
Labels: t-tooling
