Repository apify/apify-cli, pull requests merged in 2024-10, with the labels that each got.

#669 feat: `actors start`
  src/commands/actors/call.ts
  src/commands/actors/start.ts
Labels: adhoc, t-tooling

#671 feat: `actors push`
  src/commands/actors/push.ts
  src/commands/push.ts
  test/commands/call.test.ts
  test/commands/push.test.ts
  test/commands/task/run.test.ts
Labels: adhoc, t-tooling, tested

#672 fix: emit warning if input.json is modified during run and prefilled with defaults
  src/commands/run.ts
Labels: t-tooling

#675 feat: `actors ls`
  src/commands/actors/ls.ts
  src/commands/builds/ls.ts
  src/commands/runs/info.ts
  src/commands/runs/ls.ts
  src/lib/commands/responsive-table.ts
Labels: adhoc, t-tooling

#678 feat: `key-value-stores get-value`
  src/commands/key-value-stores/get-value.ts
  src/commands/key-value-stores/index.ts
  src/lib/utils.ts
  tsconfig.json
Labels: adhoc, t-tooling

#682 chore: Setup cli app for Mixpanel
  src/lib/telemetry.ts
Labels: t-web

#686 fix: scrapy wrapping being broken due to ESM migration
  src/lib/projects/scrapy/wrapScrapyProject.ts
Labels: adhoc, t-tooling
