Repository apify/apify-cli, pull requests merged in 2024-03, with the labels that each got.

#506 feat: Warn user there's newer Actor version on the platform
  CONTRIBUTING.md
  README.md
  src/commands/create.ts
  src/commands/push.ts
  test/commands/call.test.ts
  test/commands/push.test.ts
Labels: t-web, tested

#510 chore: don't print stdout at all when running tests
  src/lib/exec.ts
  src/lib/utils.ts
  vitest.config.ts
Labels: adhoc, t-tooling, tested

#513 chore: Update local dev script to allow running from anywhere
  CONTRIBUTING.md
  bin/dev.js
  bin/dev.sh
  package.json
Labels: bug, adhoc, t-platform

#521 feat: support spaces and `:` for subcommands
  docs/vars.md
  package.json
  src/commands/secrets/index.ts
  src/lib/secrets.ts
  test/commands/secrets/add.test.ts
Labels: t-tooling, tested

#523 chore: force dependency installs on actions on Windows
  .github/workflows/check.yaml
Labels: adhoc, t-tooling

#522 feat: prevent old node from running CLI
  .github/workflows/check.yaml
  bin/dev.js
  bin/run.js
  package.json
Labels: t-tooling

#520 feat: different exit codes for different errors
  src/commands/call.ts
  src/commands/push.ts
  src/lib/consts.ts
Labels: t-tooling

#524 feat: --no-optional for create command
  src/commands/create.ts
  test/commands/create.test.ts
Labels: t-tooling, tested

#528 chore(ci): move to yarn
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-postinstall-dev.cjs
  .yarnrc.yml
  package-lock.json
  package.json
  website/.gitignore
  website/.yarnrc.yml
  website/package-lock.json
  website/package.json
  website/yarn.lock
  yarn.lock
Labels: adhoc, t-tooling, tested

#530 chore(ci): fix beta flow
  .github/workflows/check.yaml
  .github/workflows/docs.yaml
Labels: adhoc, t-tooling

#532 chore: fix yarn and renovate
  .yarn/plugins/@yarnpkg/plugin-postinstall-dev.cjs
  .yarn/plugins/postinstallDev.cjs
  .yarnrc.yml
  package.json
  tsconfig.eslint.json
  yarn.lock
Labels: adhoc, t-tooling

#536 refactor: dev script should import ts files
  bin/dev.js
Labels: adhoc, t-tooling
