Repository apify/apify-cli, pull requests merged in 2024-06, with the labels that each got.

#575 chore: push updated yarn.lock too
  .github/workflows/docs.yaml
Labels: adhoc, t-tooling

#558 feat: task run, actor call, deprecate top level call
  src/commands/call.ts
  src/commands/task/index.ts
  src/commands/task/run.ts
  src/lib/commands/run-on-cloud.ts
  src/lib/utils.ts
  test/__setup__/build-utils.ts
  test/commands/call.test.ts
  test/commands/push.test.ts
  test/commands/task/run.test.ts
  test/python_support.test.ts
Labels: t-tooling, tested

#570 fix: print most information to stderr in preparation of future integrations
  src/commands/call.ts
  src/commands/create.ts
  src/commands/edit-input-schema.ts
  src/commands/init-wrap-scrapy.ts
  src/commands/init.ts
  src/commands/login.ts
  src/commands/logout.ts
  src/commands/pull.ts
  src/commands/push.ts
  src/commands/run.ts
  src/commands/validate-schema.ts
  src/hooks/deprecations.ts
  src/lib/commands/run-on-cloud.ts
  src/lib/create-utils.ts
  src/lib/exec.ts
  src/lib/input_schema.ts
  src/lib/outputs.ts
  src/lib/projects/scrapy/wrapScrapyProject.ts
  src/lib/secrets.ts
  src/lib/telemetry.ts
  src/lib/utils.ts
  src/lib/version_check.ts
  test/commands/info.test.ts
  test/commands/log_in_out.test.ts
  test/commands/push.test.ts
  test/secrets.test.ts
Labels: t-tooling, tested

#578 feat: Update api token links
  README.md
  docs/installation.md
  docs/integrating-scrapy.md
  src/commands/login.ts
  test/commands/pull.test.ts
Labels: adhoc, t-console, tested
