Repository apify/apify-cli, pull requests merged in 2024-08, with the labels that each got.

#613 fix(call): support calling with bare ids
  src/commands/call.ts
  test/commands/call.test.ts
Labels: adhoc, t-tooling, tested

#609 test: Feature file for `actor run` input
  .editorconfig
  .github/workflows/check.yaml
  .github/workflows/cucumber.yaml
  .github/workflows/docs.yaml
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  MIGRATIONS.md
  README.md
  cucumber.json
  docs/installation.md
  docs/integrating-scrapy.md
  docs/reference.md
  docs/telemetry.md
  docs/troubleshooting.md
  docs/vars.md
  features/actor-run-input.feature.md
  features/test-implementations/0.basic-actor.js
  features/test-implementations/0.world.ts
  features/test-implementations/1.setup.ts
  features/test-implementations/2.execution.ts
  features/test-implementations/3.results.ts
  features/test-implementations/README.md
  package.json
  src/commands/run.ts
  src/lib/commands/resolve-input.ts
  tsconfig.eslint.json
  yarn.lock
Labels: t-tooling

#614 feat: printing dataset result for `call` command
  src/commands/call.ts
  src/lib/commands/run-on-cloud.ts
Labels: adhoc, t-tooling

#618 fix: print path to invalid `actor.json` when an invalid file is found
  cucumber.json
  features/invalid-actor-json-output.feature.md
  features/test-implementations/1.setup.ts
  features/test-implementations/README.md
  src/commands/init.ts
  src/commands/pull.ts
  src/commands/push.ts
  src/commands/run.ts
  src/lib/consts.ts
  src/lib/utils.ts
Labels: t-tooling

#622 chore: release 0.20.5
  package.json
Labels: adhoc, t-tooling
