Repository apify/apify-cli, pull requests merged in 2025-04, with the labels that each got.

#771 Update reference-template.md
  scripts/reference-template.md
Labels: documentation, adhoc, t-docs

#772 docs: fix build badge in the readme
  README.md
Labels: adhoc, t-tooling

#773 docs: remove gh badges
  docs/index.md
  website/versioned_docs/version-0.20/index.md
  website/versioned_docs/version-0.21/index.md
  website/versioned_docs/version-0.21/reference.md
Labels: t-docs

#778 chore(release): 0.21.4
  package.json
Labels: adhoc, t-tooling

#779 chore: create .apify directory missing in one place
  src/lib/local_state.ts
Labels: adhoc, t-tooling

#781 chore: fix dependency position
  package.json
Labels: adhoc, t-tooling

#784 chore: docs fix
  docs/reference.md
  website/versioned_docs/version-0.21/reference.md
Labels: adhoc, t-tooling

#785 fix: runtime detection on Windows
  package.json
  src/lib/exec.ts
  src/lib/hooks/runtimes/javascript.ts
  src/lib/hooks/runtimes/python.ts
  src/lib/hooks/runtimes/utils.ts
Labels: adhoc, t-tooling

#786 fix: windows and python compatibility
  src/lib/exec.ts
  src/lib/hooks/runtimes/javascript.ts
  src/lib/hooks/runtimes/python.ts
  src/lib/hooks/useActorConfig.ts
  src/lib/hooks/useCwdProject.ts
  src/lib/hooks/useModuleVersion.ts
  src/lib/utils/cliDebugPrint.ts
Labels: adhoc, t-tooling

#789 chore: mask secrets in CI runs
  .github/workflows/check.yaml
  .github/workflows/cucumber.yaml
  eslint.config.mjs
  test/__setup__/config.ts
  test/__setup__/hooks/useAuthSetup.ts
  test/commands/call.test.ts
  test/commands/info.test.ts
  test/commands/log_in_out.test.ts
  test/commands/pull.test.ts
  test/commands/push.test.ts
  test/commands/run.test.ts
  test/commands/task/run.test.ts
Labels: adhoc, t-tooling, tested
