Repository apify/apify-cli, pull requests merged in 2025-08, with the labels that each got.

#865 fix(pull): handle private actors correctly
  src/commands/actors/pull.ts
  test/api/commands/pull.test.ts
Labels: t-tooling, tested

#868 chore: Setup docs llms plugin
  website/docusaurus.config.js
  website/package.json
  website/yarn.lock
Labels: t-web

#871 chore!: move from yargs to node:util
  features/test-implementations/1.setup.ts
  package.json
  src/commands/_register.ts
  src/commands/_testCommands/_FlagTests.ts
  src/commands/actors/call.ts
  src/commands/cli-management/upgrade.ts
  src/entrypoints/_shared.ts
  src/entrypoints/actor.ts
  src/entrypoints/apify.ts
  src/lib/command-framework/CommandError.ts
  src/lib/command-framework/apify-command.ts
  src/lib/command-framework/args.ts
  src/lib/command-framework/flags.ts
  src/lib/command-framework/help/CommandHelp.ts
  src/lib/command-framework/help/_BaseCommandRenderer.ts
  yarn.lock
Labels: t-tooling

#873 chore: fix node:util parseArgs migration
  scripts/install/install.sh
  src/commands/cli-management/install.ts
  src/entrypoints/_shared.ts
Labels: adhoc, t-tooling

#876 chore: fix login/logout test + make vitest wait longer for api tests
  test/api/commands/log_in_out.test.ts
  vitest.config.ts
Labels: adhoc, t-tooling, tested
