Repository apify/apify-cli, pull requests merged in 2025-02, with the labels that each got.

#737 docs: add v0.21 snapshot
  website/versioned_docs/version-0.21/changelog.md
  website/versioned_docs/version-0.21/index.md
  website/versioned_docs/version-0.21/installation.md
  website/versioned_docs/version-0.21/integrating-scrapy.md
  website/versioned_docs/version-0.21/reference.md
  website/versioned_docs/version-0.21/telemetry.md
  website/versioned_docs/version-0.21/troubleshooting.md
  website/versioned_docs/version-0.21/vars.md
  website/versioned_sidebars/version-0.21-sidebars.json
  website/versions.json
Labels: adhoc, t-tooling

#741 fix: emit logs to stderr when actors are started with `--json` flag
  src/commands/actors/call.ts
Labels: t-tooling

#742 chore(ci): fix release flow
  .github/workflows/release.yaml
  CHANGELOG.md
  README.md
  docs/reference.md
  package.json
Labels: adhoc, t-tooling

#743 chore(ci): fix homebrew step
  .github/workflows/release.yaml
Labels: adhoc, t-tooling

#748 feat: actor charge command
  .gitignore
  src/commands/actor/charge.ts
  src/lib/actor.ts
Labels: t-c&c

#753 ci: Fix pre-release
  .github/scripts/before-beta-release.ts
  .github/workflows/pre_release.yaml
Labels: adhoc, t-tooling

#754 ci: Fix pre-release
  .github/workflows/pre_release.yaml
Labels: adhoc, t-tooling
